global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['172.31.173.87:9249','172.31.173.87:9250']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'go-api'
    static_configs:
      - targets: ['api:2112']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']